#!/bin/bash
# Quick Start Guide for Raman Spectroscopy Analysis

# ============================================
# INSTALLATION
# ============================================

echo "Installing dependencies..."
pip install -r requirements.txt

echo "✅ Installation complete!"

# ============================================
# USAGE
# ============================================

echo ""
echo "=========================================="
echo "  INTERACTIVE ANALYSIS (RECOMMENDED)"
echo "=========================================="
echo ""
echo "Run this command:"
echo ""
echo "    python interactive_analysis.py"
echo ""
echo "Then follow the step-by-step prompts to:"
echo "  1. Load your spectrum file"
echo "  2. Specify wavelength format (nm or cm⁻¹)"
echo "  3. Enter laser wavelength"
echo "  4. Configure preprocessing parameters"
echo "  5. Set peak detection sensitivity"
echo "  6. Choose peak models"
echo "  7. Set output preferences"
echo ""

echo "=========================================="
echo "  PROGRAMMATIC USAGE"
echo "=========================================="
echo ""
echo "For advanced users, use the universal pipeline:"
echo ""
echo "    from universal_raman_advanced import universal_raman_analysis"
echo "    import numpy as np"
echo ""
echo "    # Load your data"
echo "    data = np.loadtxt('my_spectrum.txt', delimiter='\\t')"
echo "    x = data[:, 0]  # Raman shift in cm⁻¹"
echo "    y = data[:, 1]  # Intensity"
echo ""
echo "    # Run analysis"
echo "    result, metrics = universal_raman_analysis("
echo "        x, y,"
echo "        output_prefix='my_analysis'"
echo "    )"
echo ""

echo "=========================================="
echo "  OUTPUT FILES"
echo "=========================================="
echo ""
echo "For output_prefix='my_analysis', you get:"
echo ""
echo "  📊 my_analysis_metrics.csv"
echo "     Peak parameters (center, FWHM, amplitude, etc.)"
echo ""
echo "  📈 my_analysis_spectrum.csv"
echo "     Full spectral data (raw, processed, fit, baseline)"
echo ""
echo "  📋 my_analysis_report.txt"
echo "     Detailed fit statistics and parameters"
echo ""
echo "  🖼️  my_analysis.png"
echo "     Publication-quality plot (300 DPI)"
echo ""
echo "  📄 my_analysis.pdf"
echo "     Vector format for publications"
echo ""

echo "=========================================="
echo "  FEATURES"
echo "=========================================="
echo ""
echo "✅ Automatic peak detection (no manual guessing)"
echo "✅ Intelligent model selection per peak"
echo "✅ Robust baseline subtraction (airPLS algorithm)"
echo "✅ Cosmic ray removal"
echo "✅ Physical constraints (NO negative peaks)"
echo "✅ Publication-ready visualizations"
echo "✅ Works for halide perovskites & all materials"
echo ""

echo "=========================================="
echo "  EXAMPLE DATA"
echo "=========================================="
echo ""
echo "Create a sample spectrum file 'sample.txt':"
echo ""
echo "    # Raman Shift (cm-1)    Intensity (a.u.)"
echo "    100                      150"
echo "    101                      155"
echo "    102                      160"
echo "    ..."
echo "    1000                     2500"
echo ""

echo "=========================================="
echo "  TROUBLESHOOTING"
echo "=========================================="
echo ""
echo "Problem: No peaks detected"
echo "Solution: Run interactive_analysis.py and lower the prominence ratio"
echo ""
echo "Problem: Peaks not fitting well"
echo "Solution: Try different laser wavelength or check data format"
echo ""
echo "Problem: Negative baseline"
echo "Solution: Increase airpls_lambda value"
echo ""

echo "=========================================="
echo "  CONTACT & SUPPORT"
echo "=========================================="
echo ""
echo "Repository: https://github.com/Anas0zouhair/raman-perovskite-analysis"
echo ""
